filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/app/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message
  fields:
    type: application_logs
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/app/test/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message
  fields:
    type: test_logs
  fields_under_root: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_kubernetes_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644 